-- List of 6 votes
votes = [
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Rachet","Clank","Sly Racoon","Jak","Daxter"],
            ["Clank","Rachet","Sly Racoon","Jak","Daxter"],
            ["Sly Racoon","Rachet","Clank","Daxter","Jak"]
        ]

seats = 5

getQuota = (length votes `div` (seats + 1)) + 1